const products = [
  {
    id: 1,
    name: "AirPods Pro Max",
    category: "Electronics",
    price: 249.99,
    originalPrice: 349.99,
    rating: 4.8,
    reviews: 1240,
    badge: "Best Seller",
    description: "Premium wireless headphones with active noise cancellation, spatial audio, and up to 20 hours of battery life. Comes with a smart case for extended listening.",
    features: ["Active Noise Cancellation", "Spatial Audio", "20hr Battery", "Smart Case", "Lightning Connector"],
    colors: ["Space Gray", "Silver", "Sky Blue", "Pink"],
    stock: 15,
    emoji: "🎧"
  },
  {
    id: 2,
    name: "Ultrabook Pro 14",
    category: "Electronics",
    price: 1199.99,
    originalPrice: 1499.99,
    rating: 4.9,
    reviews: 867,
    badge: "New",
    description: "Ultra-thin laptop with a stunning 14-inch OLED display, 12-core processor, and all-day battery life. Perfect for creators and professionals.",
    features: ["14\" OLED Display", "12-Core CPU", "16GB RAM", "512GB SSD", "Backlit Keyboard"],
    colors: ["Midnight Black", "Arctic Silver", "Rose Gold"],
    stock: 8,
    emoji: "💻"
  },
  {
    id: 3,
    name: "SmartWatch Series X",
    category: "Electronics",
    price: 329.99,
    originalPrice: 399.99,
    rating: 4.7,
    reviews: 2103,
    badge: "Sale",
    description: "Next-gen smartwatch with always-on AMOLED display, health monitoring suite including SpO2, ECG, and GPS with 100+ workout modes.",
    features: ["AMOLED Display", "ECG Monitor", "Built-in GPS", "45-Day Battery", "Water Resistant"],
    colors: ["Black", "Silver", "Gold", "Midnight Blue"],
    stock: 22,
    emoji: "⌚"
  },
  {
    id: 4,
    name: "Leather Crossbody Bag",
    category: "Fashion",
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.6,
    reviews: 532,
    badge: "Sale",
    description: "Handcrafted genuine leather crossbody bag with adjustable strap, multiple compartments, and a timeless design for everyday use.",
    features: ["Genuine Leather", "Adjustable Strap", "Multiple Pockets", "Magnetic Closure", "RFID Protection"],
    colors: ["Tan", "Black", "Burgundy", "Camel"],
    stock: 30,
    emoji: "👜"
  },
  {
    id: 5,
    name: "Running Shoes Pro",
    category: "Fashion",
    price: 119.99,
    originalPrice: 159.99,
    rating: 4.5,
    reviews: 3420,
    badge: "Best Seller",
    description: "Lightweight performance running shoes with responsive foam cushioning, breathable mesh upper, and durable rubber outsole for all terrains.",
    features: ["Responsive Foam", "Breathable Mesh", "Anti-slip Sole", "Reflective Details", "Removable Insole"],
    colors: ["White/Blue", "Black/Red", "Grey/Yellow", "Navy/Orange"],
    stock: 50,
    emoji: "👟"
  },
  {
    id: 6,
    name: "Casual Hoodie Premium",
    category: "Fashion",
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.4,
    reviews: 891,
    badge: null,
    description: "Ultra-soft premium cotton hoodie with a relaxed fit, kangaroo pocket, and adjustable drawstring. Pre-washed for a vintage feel.",
    features: ["100% Cotton", "Relaxed Fit", "Kangaroo Pocket", "Pre-washed Fabric", "Machine Washable"],
    colors: ["Charcoal", "Cream", "Forest Green", "Navy", "Dusty Rose"],
    stock: 40,
    emoji: "🧥"
  },
  {
    id: 7,
    name: "Portable Blender",
    category: "Home & Kitchen",
    price: 44.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 1560,
    badge: "New",
    description: "USB-rechargeable portable blender with 6 stainless steel blades. Makes fresh smoothies anywhere in seconds with a 400ml BPA-free cup.",
    features: ["USB Rechargeable", "6 Steel Blades", "400ml Capacity", "BPA-Free", "Self-Cleaning"],
    colors: ["White", "Black", "Mint Green", "Coral"],
    stock: 35,
    emoji: "🥤"
  },
  {
    id: 8,
    name: "Smart LED Desk Lamp",
    category: "Home & Kitchen",
    price: 69.99,
    originalPrice: 89.99,
    rating: 4.7,
    reviews: 743,
    badge: null,
    description: "Eye-caring desk lamp with touch-sensitive controls, 10 brightness levels, 5 color temperatures, wireless charging pad, and USB-A port.",
    features: ["Wireless Charging", "10 Brightness Levels", "5 Color Temps", "Touch Control", "USB-A Port"],
    colors: ["White", "Black"],
    stock: 18,
    emoji: "💡"
  },
  {
    id: 9,
    name: "Ceramic Coffee Set",
    category: "Home & Kitchen",
    price: 54.99,
    originalPrice: 74.99,
    rating: 4.8,
    reviews: 420,
    badge: "Sale",
    description: "Handmade ceramic coffee set with 4 cups and a matching tray. Microwave and dishwasher safe with a minimalist matte glaze finish.",
    features: ["Handmade Ceramic", "Set of 4 Cups", "Microwave Safe", "Dishwasher Safe", "Matching Tray"],
    colors: ["Matte White", "Sage Green", "Terracotta", "Navy"],
    stock: 12,
    emoji: "☕"
  },
  {
    id: 10,
    name: "Yoga Mat Premium",
    category: "Sports",
    price: 75.99,
    originalPrice: 99.99,
    rating: 4.9,
    reviews: 2890,
    badge: "Best Seller",
    description: "Extra-thick non-slip yoga mat made from natural tree rubber. Includes alignment lines, carrying strap, and a microfiber cleaning cloth.",
    features: ["Natural Tree Rubber", "6mm Thickness", "Alignment Lines", "Non-Slip Surface", "Carrying Strap"],
    colors: ["Deep Purple", "Ocean Blue", "Charcoal", "Blush Pink"],
    stock: 60,
    emoji: "🧘"
  },
  {
    id: 11,
    name: "Resistance Band Set",
    category: "Sports",
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.5,
    reviews: 4100,
    badge: "Sale",
    description: "Set of 5 resistance bands with varying tension levels (10–50 lbs). Made from natural latex with anti-snap technology. Includes a carry bag.",
    features: ["5 Resistance Levels", "Natural Latex", "Anti-Snap", "Carry Bag Included", "Beginner to Pro"],
    colors: ["Multicolor Set"],
    stock: 100,
    emoji: "💪"
  },
  {
    id: 12,
    name: "Wireless Gaming Mouse",
    category: "Electronics",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 1832,
    badge: "New",
    description: "Ultra-lightweight wireless gaming mouse with 25,000 DPI optical sensor, 70-hour battery life, and customizable RGB lighting with 11 buttons.",
    features: ["25,000 DPI Sensor", "70hr Battery", "RGB Lighting", "11 Programmable Buttons", "2.4GHz Wireless"],
    colors: ["Matte Black", "White"],
    stock: 25,
    emoji: "🖱️"
  },
  {
    id: 13,
    name: "Noise-Cancelling Earbuds",
    category: "Electronics",
    price: 129.99,
    originalPrice: 179.99,
    rating: 4.6,
    reviews: 1045,
    badge: "Best Seller",
    description: "Compact true wireless earbuds with adaptive noise cancellation, environmental sound mode, and up to 24 hours of combined playback.",
    features: ["Adaptive ANC", "Touch Controls", "IPX4 Water Resistant", "24hr Playtime", "Fast Charging"],
    colors: ["Midnight Black", "Pearl White", "Lavender"],
    stock: 42,
    emoji: "🎧"
  },
  {
    id: 14,
    name: "Minimalist Travel Backpack",
    category: "Fashion",
    price: 64.99,
    originalPrice: 89.99,
    rating: 4.5,
    reviews: 680,
    badge: null,
    description: "Lightweight travel backpack with a padded laptop sleeve, hidden anti-theft pocket, and water-resistant exterior for everyday adventures.",
    features: ["Anti-Theft Pocket", "Laptop Sleeve", "Water-Resistant", "Airflow Back Panel", "Organized Compartments"],
    colors: ["Slate Gray", "Forest Green", "Midnight Navy"],
    stock: 28,
    emoji: "🎒"
  },
  {
    id: 15,
    name: "Smart Indoor Garden",
    category: "Home & Kitchen",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.8,
    reviews: 512,
    badge: "New",
    description: "Compact smart garden kit with automated LED grow lights, self-watering system, and curated seed pods for fresh herbs year-round.",
    features: ["Auto Watering", "LED Grow Light", "Eco-Friendly", "Starter Seed Pods", "App Notifications"],
    colors: ["White", "Sage"],
    stock: 19,
    emoji: "🌿"
  },
  {
    id: 16,
    name: "Performance Bike Helmet",
    category: "Sports",
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.6,
    reviews: 1297,
    badge: "Sale",
    description: "Aerodynamic cycling helmet with removable visor, advanced ventilation, and MIPS protection for safe, stylish rides.",
    features: ["MIPS Safety", "Aerodynamic Shell", "Ventilated Design", "Removable Visor", "Adjustable Fit"],
    colors: ["Carbon Black", "Ice Blue", "Neon Yellow"],
    stock: 34,
    emoji: "🚴"
  },
  {
    id: 17,
    name: "Classic Canvas Tote",
    category: "Fashion",
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 520,
    badge: null,
    description: "Durable canvas tote bag with reinforced handles and a structured base for everyday shopping or travel.",
    features: ["Reinforced Handles", "Structured Base", "Easy Care", "Spacious Interior", "Eco-Friendly"],
    colors: ["Natural", "Black"],
    stock: 84,
    emoji: "🛍️"
  },
  {
    id: 18,
    name: "Portable Coffee Press",
    category: "Home & Kitchen",
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.7,
    reviews: 312,
    badge: "New",
    description: "Stainless steel travel coffee press with insulated sleeve and spill-proof lid. Brew fresh coffee on the go.",
    features: ["Stainless Steel", "Insulated Sleeve", "Spill-Proof Lid", "Quick Brew", "Travel Friendly"],
    colors: ["Matte Black", "Steel"],
    stock: 48,
    emoji: "☕"
  },
  {
    id: 19,
    name: "Street Style Sunglasses",
    category: "Fashion",
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviews: 740,
    badge: "Best Seller",
    description: "Modern polarized sunglasses with anti-glare lenses and lightweight metal frame. Perfect for city style.",
    features: ["Polarized Lenses", "Anti-Glare", "Lightweight Frame", "UV400 Protection", "Comfort Fit"],
    colors: ["Matte Black", "Silver"],
    stock: 55,
    emoji: "🕶️"
  },
  {
    id: 20,
    name: "Compact Fitness Tracker",
    category: "Sports",
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviews: 1012,
    badge: "Sale",
    description: "Slim fitness tracker with heart rate monitoring, sleep tracking, and step counter. Ideal for active lifestyles.",
    features: ["Heart Rate Monitor", "Sleep Tracking", "Step Counter", "Water Resistant", "Lightweight"],
    colors: ["Black", "White"],
    stock: 67,
    emoji: "⌚"
  }
];
